schema {
    query: Query
    mutation: Mutation
}

type Query {
    stringField: String!
    variousScalars: VariousScalars!
    lists: Lists!

    scalarsInput(arg: VariousScalarsInput!): String!
    listsInput(arg: ListsInput!): String!

    dogOrHuman: DogOrHuman!
}

type Mutation {
    mutationWithError: MutationWithErrorResult!
}

type MutationWithErrorResult {
    value: SampleResult
    errors: [SampleError!]
}

type SampleResult {
    stringField: String!
}

type SampleError {
    field: SampleField!
    message: String!
}

enum SampleField {
    FIRST
    SECOND
    THIRD
}

type VariousScalars {
    nullableString: String
    string: String!
    nullableInt: Int
    int: Int!
    nullableFloat: Float
    float: Float!
    nullableBoolean: Boolean
    boolean: Boolean!
    nullableID: ID
    id: ID!
}

type Lists {
    nullableOfNullable: [String]
    nullableOfNonNullable: [String!]
    nonNullableOfNullable: [String]!
    nonNullableOfNonNullable: [String!]!
}

input VariousScalarsInput {
    nullableString: String
    string: String!
    nullableInt: Int
    int: Int!
    nullableFloat: Float
    float: Float!
    nullableBoolean: Boolean
    boolean: Boolean!
    nullableID: ID
    id: ID!
}

input ListsInput {
    nullableOfNullable: [String]
    nullableOfNonNullable: [String!]
    nonNullableOfNullable: [String]!
    nonNullableOfNonNullable: [String!]!
}

type Dog {
    name: String!
    barkVolume: Float!
}

type Human {
    name: String!
}

union DogOrHuman = Dog | Human